# -*- coding: utf-8 -*-
"""RQ7_diversity.ipynb

Automatically generated by Colab.


# RQ7

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

# Create output directory if it doesn't exist
output_dir =  'results\RQ7' #'../../results/RQ7'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

"""## import dataframe"""

df = pd.read_csv('data\q28_q29.csv')


"""##  Distribution of “Yes” and “No” responses to Question 28

"""

print(df['28'].value_counts())

#220 = 100
# 142 = x

print(142*100/220)

print(78*100/220)

# yes + no

print(64.5 + 35.4)

# Distribution of “Yes” and “No” responses to Question 28 by gender.

df_gender = df[df["Gender"] != "Others/I don't know"]
sns.countplot(data=df_gender, x='28', stat="percent", hue= "Gender")
plt.savefig(f'{output_dir}/bar_q28_gen.png', dpi=300, bbox_inches='tight')
plt.show()

# Distribution of “Yes” and “No” responses to Question 28 by Sexuality
df_sexuality = df[df["Sexuality"] != "Others/I don't know"]
sns.countplot(data=df_sexuality, x='28', stat="percent", hue= "Sexuality")
plt.savefig(f'{output_dir}/bar_q28_se.png', bbox_inches="tight")
plt.show()

# Distribution of “Yes” and “No” responses to Question 28 by Race
df_race = df[df["Race"] != "Others/I don't know"]
sns.countplot(data=df_race, x='28', stat="percent", hue= "Race")
plt.savefig(f'{output_dir}/bar_q28_race.png', bbox_inches="tight")
plt.show()

#  Distribution of “Yes” and “No” responses to Question 28 by Disabled
df_disabled = df[df["Disabled"] != "Others/I don't know"]
sns.countplot(data=df_disabled, x='28', stat="percent", hue= "Disabled")
plt.savefig(f'{output_dir}/bar_q28_dis.png', dpi=300, bbox_inches='tight')

plt.show()

"""## Responses to Question 29

### data cleaning and preprocessing
"""

df['28'] = df['28'].str.lower()
df['29'] = df['29'].astype(str).str.lower()

def discourse_strategy(row):
    if row['28'] == 'no':
        return 'no_recognition'
    elif row['28'] == 'yes' and (row['29'] == 'none' or row['29'] == 'nan'):
        return 'recognized_no_narrative'
    elif row['28'] == 'yes' and row['report_type'] == '3S':
        return 'third_person'
    elif row['28'] == 'yes' and row['report_type'] == '1S':
        return 'first_person'
    else:
        return np.nan

df['discourse_strategy'] = df.apply(discourse_strategy, axis=1)

df1 = df[(df['28'] == 'yes')&(df['29'] != 'none')]

# distribution to Question 29:
#19 records classified as “none”
# 59 records containing descriptions of facts.
print(19+59)

# Responses that answered “Yes” to Question 28 and reported facts in Question 29.
# 220 = 100
# 59 = x
print(59*100/220)

# Responses that answered “Yes” to Question 28 but provided no report in Question 29.
#220 = 100
#19 = x
print(19*100/220)

# The percentages were verified and are correct (approximately 35.4% or 35.5%).
print(26.8+8.6)

"""### distribution discourse strategy Q28 and Q29


"""

sns.countplot(data=df, x='28', stat="percent", hue= "discourse_strategy")
plt.savefig(f'{output_dir}/bar_discourse.png', bbox_inches="tight")
plt.show()

"""###  Heatmap discourse by group"""

identity_columns = ['Disabled','Gender','Race',"Seniority", 'Sexuality' ]

df_long = df.melt(
    id_vars=['discourse_strategy'],
    value_vars=identity_columns,
    var_name='identity_dimension',
    value_name='identity_group'
)


# >>> REMOVE Others/I don't know <<<
df_long = df_long[
    df_long['identity_group'] != "Others/I don't know"
]

df_long['identity_label'] = (df_long['identity_dimension'] + ": " + df_long['identity_group'])

order = [
    'no_recognition',
    'recognized_no_narrative',
    'third_person',
    'first_person'
]

contingency = pd.crosstab(
    df_long['identity_label'],
    df_long['discourse_strategy'],
    normalize='index'
)

contingency = contingency[order]

# change label

label_map = {
    "Gender: Woman": "Women",
    "Gender: Man": "Men",
    "Sexuality: Heterosexual": "Heterosexual",
    "Sexuality: LGBTQ+": "LGBTQ+",
    "Race: White": "White",
    "Race: Non-white": "Non-white",
    "Seniority: Intern": "Intern",
    "Seniority: Junior": "Junior",
    "Seniority: Mid-level": "Mid-level",
    "Seniority: Senior": "Senior",
    "Disabled: No": "Not disabled",
    "Disabled: Yes": "Disabled"
}

contingency = contingency.rename(index=label_map)


# plot
plt.figure(figsize=(10, 6))
sns.heatmap(
    contingency * 100,
    annot=True,
    fmt=".1f",
    cmap="Reds",
    vmax= 80,
    cbar_kws={"label": "% of responses"}
)

plt.xlabel(" ")
plt.ylabel(" ")
plt.tight_layout()
plt.savefig(f'{output_dir}/heatmap29_dis.png', bbox_inches="tight")
plt.show()

"""
## category Q29

"""

df['report_category_clean'] = (
    df['report_category']
    .fillna('')
    .astype(str)
    .str.lower()
    .str.strip()
)

df_clean = df[df['report_category_clean'].apply(len) > 0]

df_clean['report_category_list'] = df_clean['report_category_clean'].apply(
    lambda x: [i.strip() for i in x.split(', ') if i.strip() != '']
)

"""### Distribution categories"""

from collections import Counter

# Flatten das categorias
all_tags = [tag for sublist in df_clean['report_category_list'] for tag in sublist]

# Contagem
tag_counts = Counter(all_tags)

# Total de ocorrências
total = sum(tag_counts.values())

# Converter para porcentagem
tag_percent = {
    k: (v / total) * 100
    for k, v in tag_counts.items()
}

# Plot
plt.figure(figsize=(8, 5))
plt.bar(tag_percent.keys(), tag_percent.values())

plt.ylabel("Percentage (%)")
plt.xticks(rotation=45, ha="right")
plt.title("Distribution of Discrimination Categories")
plt.tight_layout()
plt.savefig("barplot_cat.png", bbox_inches="tight")
plt.show()

"""
### Heatmap category by group

"""

# preparations
df_cat = df_clean.explode('report_category_list')
identity_columns = ['Disabled','Gender','Race',"Seniority", 'Sexuality' ]

df_long = df_cat.melt(
    id_vars=['report_category_list'],
    value_vars=identity_columns,
    var_name='identity_dimension',
    value_name='identity_group'
)

# remove NAN values
df_long = df_long.dropna(subset=['identity_group'])

# >>> REMOVE Others/I don't know <<<
df_long = df_long[
    df_long['identity_group'] != "Others/I don't know"
]

df_long['identity_label'] = (df_long['identity_dimension'] + ": " + df_long['identity_group'])

contingency = pd.crosstab(
    df_long['identity_label'],
    df_long['report_category_list'],
    normalize='index'
)

# change label

label_map = {
    "Gender: Woman": "Women",
    "Gender: Man": "Men",
    "Sexuality: Heterosexual": "Heterosexual",
    "Sexuality: LGBTQ+": "LGBTQ+",
    "Race: White": "White",
    "Race: Non-white": "Non-white",
    "Seniority: Intern": "Intern",
    "Seniority: Junior": "Junior",
    "Seniority: Mid-level": "Mid-level",
    "Seniority: Senior": "Senior",
    "Disabled: No": "Not disabled",
    "Disabled: Yes": "Disabled"
}

contingency = contingency.rename(index=label_map)


# plot
plt.figure(figsize=(10, 6))
sns.heatmap(
    contingency * 100,
    annot=True,
    fmt=".1f",
    cmap="Reds",
    vmax= 80,
    cbar_kws={"label": "% of responses"}
)

plt.xlabel(" ")
plt.ylabel(" ")
plt.tight_layout()
plt.savefig(f'{output_dir}/heatmap29_cat.png', bbox_inches="tight")
plt.show()

"""### Userplot Category"""

from upsetplot import from_memberships, UpSet

memberships = df_clean['report_category_list'].tolist()

upset_data = from_memberships(memberships)

# 🔥 FIX CRÍTICO: converter MultiIndex para booleano
upset_data.index = upset_data.index.map(
    lambda x: tuple(bool(i) for i in x)
)

up = UpSet(
    upset_data,
    subset_size="count",
    show_counts=True,
    sort_by="cardinality"
)

up.plot()


plt.gcf().suptitle(
    "Intersections Between Report Categories",
    fontsize=14,
    fontweight="bold",
    y=1.02
)

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig(f'{output_dir}/useplot_cat2.png', bbox_inches="tight")
plt.show()

# to verify userplot
from collections import Counter

print(Counter(tuple(sorted(x)) for x in memberships).most_common(10))